name: lcov_dart
version: 7.0.0

description: Parse and format to LCOV your code coverage reports. The best way to share your code coverage stats.
homepage: https://github.com/MohiuddinM/lcov.dart
issue_tracker: https://github.com/MohiuddinM/lcov.dart/issues
repository: https://github.com/MohiuddinM/lcov.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.12.1
  coverage: ^1.0.1
  test: ^1.16.7
